<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.AckAllQueueMessagesResponse</code>
 */
class AckAllQueueMessagesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     */
    protected $RequestID = '';
    /**
     * Generated from protobuf field <code>uint64 AffectedMessages = 2;</code>
     */
    protected $AffectedMessages = 0;
    /**
     * Generated from protobuf field <code>bool IsError = 3;</code>
     */
    protected $IsError = false;
    /**
     * Generated from protobuf field <code>string Error = 4;</code>
     */
    protected $Error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RequestID
     *     @type int|string $AffectedMessages
     *     @type bool $IsError
     *     @type string $Error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @return string
     */
    public function getRequestID()
    {
        return $this->RequestID;
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestID($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 AffectedMessages = 2;</code>
     * @return int|string
     */
    public function getAffectedMessages()
    {
        return $this->AffectedMessages;
    }

    /**
     * Generated from protobuf field <code>uint64 AffectedMessages = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAffectedMessages($var)
    {
        GPBUtil::checkUint64($var);
        $this->AffectedMessages = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsError = 3;</code>
     * @return bool
     */
    public function getIsError()
    {
        return $this->IsError;
    }

    /**
     * Generated from protobuf field <code>bool IsError = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsError($var)
    {
        GPBUtil::checkBool($var);
        $this->IsError = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Error = 4;</code>
     * @return string
     */
    public function getError()
    {
        return $this->Error;
    }

    /**
     * Generated from protobuf field <code>string Error = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->Error = $var;

        return $this;
    }

}

