<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string EventID = 1;</code>
     */
    protected $EventID = '';
    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     */
    protected $ClientID = '';
    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     */
    protected $Channel = '';
    /**
     * Generated from protobuf field <code>string Metadata = 4;</code>
     */
    protected $Metadata = '';
    /**
     * Generated from protobuf field <code>bytes Body = 5;</code>
     */
    protected $Body = '';
    /**
     * Generated from protobuf field <code>bool Store = 6;</code>
     */
    protected $Store = false;
    /**
     * Generated from protobuf field <code>map<string, string> Tags = 7;</code>
     */
    private $Tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $EventID
     *     @type string $ClientID
     *     @type string $Channel
     *     @type string $Metadata
     *     @type string $Body
     *     @type bool $Store
     *     @type array|\Google\Protobuf\Internal\MapField $Tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string EventID = 1;</code>
     * @return string
     */
    public function getEventID()
    {
        return $this->EventID;
    }

    /**
     * Generated from protobuf field <code>string EventID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventID($var)
    {
        GPBUtil::checkString($var, True);
        $this->EventID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @return string
     */
    public function getClientID()
    {
        return $this->ClientID;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ClientID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Metadata = 4;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->Metadata;
    }

    /**
     * Generated from protobuf field <code>string Metadata = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->Metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 5;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->Body;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->Body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Store = 6;</code>
     * @return bool
     */
    public function getStore()
    {
        return $this->Store;
    }

    /**
     * Generated from protobuf field <code>bool Store = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setStore($var)
    {
        GPBUtil::checkBool($var);
        $this->Store = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Tags = 7;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->Tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Tags = 7;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Tags = $arr;

        return $this;
    }

}

