<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.PingResult</code>
 */
class PingResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Host = 1;</code>
     */
    protected $Host = '';
    /**
     * Generated from protobuf field <code>string Version = 2;</code>
     */
    protected $Version = '';
    /**
     * Generated from protobuf field <code>int64 ServerStartTime = 3;</code>
     */
    protected $ServerStartTime = 0;
    /**
     * Generated from protobuf field <code>int64 ServerUpTimeSeconds = 4;</code>
     */
    protected $ServerUpTimeSeconds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Host
     *     @type string $Version
     *     @type int|string $ServerStartTime
     *     @type int|string $ServerUpTimeSeconds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Host = 1;</code>
     * @return string
     */
    public function getHost()
    {
        return $this->Host;
    }

    /**
     * Generated from protobuf field <code>string Host = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->Host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->Version;
    }

    /**
     * Generated from protobuf field <code>string Version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ServerStartTime = 3;</code>
     * @return int|string
     */
    public function getServerStartTime()
    {
        return $this->ServerStartTime;
    }

    /**
     * Generated from protobuf field <code>int64 ServerStartTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServerStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->ServerStartTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ServerUpTimeSeconds = 4;</code>
     * @return int|string
     */
    public function getServerUpTimeSeconds()
    {
        return $this->ServerUpTimeSeconds;
    }

    /**
     * Generated from protobuf field <code>int64 ServerUpTimeSeconds = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServerUpTimeSeconds($var)
    {
        GPBUtil::checkInt64($var);
        $this->ServerUpTimeSeconds = $var;

        return $this;
    }

}

