<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.QueueMessage</code>
 */
class QueueMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string MessageID = 1;</code>
     */
    protected $MessageID = '';
    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     */
    protected $ClientID = '';
    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     */
    protected $Channel = '';
    /**
     * Generated from protobuf field <code>string Metadata = 4;</code>
     */
    protected $Metadata = '';
    /**
     * Generated from protobuf field <code>bytes Body = 5;</code>
     */
    protected $Body = '';
    /**
     * Generated from protobuf field <code>map<string, string> Tags = 6;</code>
     */
    private $Tags;
    /**
     * Generated from protobuf field <code>.kubemq.QueueMessageAttributes Attributes = 7;</code>
     */
    protected $Attributes = null;
    /**
     * Generated from protobuf field <code>.kubemq.QueueMessagePolicy Policy = 8;</code>
     */
    protected $Policy = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $MessageID
     *     @type string $ClientID
     *     @type string $Channel
     *     @type string $Metadata
     *     @type string $Body
     *     @type array|\Google\Protobuf\Internal\MapField $Tags
     *     @type \Kubemq\QueueMessageAttributes $Attributes
     *     @type \Kubemq\QueueMessagePolicy $Policy
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string MessageID = 1;</code>
     * @return string
     */
    public function getMessageID()
    {
        return $this->MessageID;
    }

    /**
     * Generated from protobuf field <code>string MessageID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageID($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @return string
     */
    public function getClientID()
    {
        return $this->ClientID;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ClientID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Metadata = 4;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->Metadata;
    }

    /**
     * Generated from protobuf field <code>string Metadata = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->Metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 5;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->Body;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->Body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Tags = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->Tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Tags = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kubemq.QueueMessageAttributes Attributes = 7;</code>
     * @return \Kubemq\QueueMessageAttributes
     */
    public function getAttributes()
    {
        return isset($this->Attributes) ? $this->Attributes : null;
    }

    public function hasAttributes()
    {
        return isset($this->Attributes);
    }

    public function clearAttributes()
    {
        unset($this->Attributes);
    }

    /**
     * Generated from protobuf field <code>.kubemq.QueueMessageAttributes Attributes = 7;</code>
     * @param \Kubemq\QueueMessageAttributes $var
     * @return $this
     */
    public function setAttributes($var)
    {
        GPBUtil::checkMessage($var, \Kubemq\QueueMessageAttributes::class);
        $this->Attributes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kubemq.QueueMessagePolicy Policy = 8;</code>
     * @return \Kubemq\QueueMessagePolicy
     */
    public function getPolicy()
    {
        return isset($this->Policy) ? $this->Policy : null;
    }

    public function hasPolicy()
    {
        return isset($this->Policy);
    }

    public function clearPolicy()
    {
        unset($this->Policy);
    }

    /**
     * Generated from protobuf field <code>.kubemq.QueueMessagePolicy Policy = 8;</code>
     * @param \Kubemq\QueueMessagePolicy $var
     * @return $this
     */
    public function setPolicy($var)
    {
        GPBUtil::checkMessage($var, \Kubemq\QueueMessagePolicy::class);
        $this->Policy = $var;

        return $this;
    }

}

