<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.QueueMessagesBatchRequest</code>
 */
class QueueMessagesBatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string BatchID = 1;</code>
     */
    protected $BatchID = '';
    /**
     * Generated from protobuf field <code>repeated .kubemq.QueueMessage Messages = 2;</code>
     */
    private $Messages;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $BatchID
     *     @type \Kubemq\QueueMessage[]|\Google\Protobuf\Internal\RepeatedField $Messages
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string BatchID = 1;</code>
     * @return string
     */
    public function getBatchID()
    {
        return $this->BatchID;
    }

    /**
     * Generated from protobuf field <code>string BatchID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBatchID($var)
    {
        GPBUtil::checkString($var, True);
        $this->BatchID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .kubemq.QueueMessage Messages = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMessages()
    {
        return $this->Messages;
    }

    /**
     * Generated from protobuf field <code>repeated .kubemq.QueueMessage Messages = 2;</code>
     * @param \Kubemq\QueueMessage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Kubemq\QueueMessage::class);
        $this->Messages = $arr;

        return $this;
    }

}

