<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.QueueMessagePolicy</code>
 */
class QueueMessagePolicy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ExpirationSeconds = 1;</code>
     */
    protected $ExpirationSeconds = 0;
    /**
     * Generated from protobuf field <code>int32 DelaySeconds = 2;</code>
     */
    protected $DelaySeconds = 0;
    /**
     * Generated from protobuf field <code>int32 MaxReceiveCount = 3;</code>
     */
    protected $MaxReceiveCount = 0;
    /**
     * Generated from protobuf field <code>string MaxReceiveQueue = 4;</code>
     */
    protected $MaxReceiveQueue = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ExpirationSeconds
     *     @type int $DelaySeconds
     *     @type int $MaxReceiveCount
     *     @type string $MaxReceiveQueue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ExpirationSeconds = 1;</code>
     * @return int
     */
    public function getExpirationSeconds()
    {
        return $this->ExpirationSeconds;
    }

    /**
     * Generated from protobuf field <code>int32 ExpirationSeconds = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setExpirationSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->ExpirationSeconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 DelaySeconds = 2;</code>
     * @return int
     */
    public function getDelaySeconds()
    {
        return $this->DelaySeconds;
    }

    /**
     * Generated from protobuf field <code>int32 DelaySeconds = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDelaySeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->DelaySeconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 MaxReceiveCount = 3;</code>
     * @return int
     */
    public function getMaxReceiveCount()
    {
        return $this->MaxReceiveCount;
    }

    /**
     * Generated from protobuf field <code>int32 MaxReceiveCount = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxReceiveCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->MaxReceiveCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string MaxReceiveQueue = 4;</code>
     * @return string
     */
    public function getMaxReceiveQueue()
    {
        return $this->MaxReceiveQueue;
    }

    /**
     * Generated from protobuf field <code>string MaxReceiveQueue = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMaxReceiveQueue($var)
    {
        GPBUtil::checkString($var, True);
        $this->MaxReceiveQueue = $var;

        return $this;
    }

}

