<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.QueueMessagesBatchResponse</code>
 */
class QueueMessagesBatchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string BatchID = 1;</code>
     */
    protected $BatchID = '';
    /**
     * Generated from protobuf field <code>repeated .kubemq.SendQueueMessageResult Results = 2;</code>
     */
    private $Results;
    /**
     * Generated from protobuf field <code>bool HaveErrors = 3;</code>
     */
    protected $HaveErrors = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $BatchID
     *     @type \Kubemq\SendQueueMessageResult[]|\Google\Protobuf\Internal\RepeatedField $Results
     *     @type bool $HaveErrors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string BatchID = 1;</code>
     * @return string
     */
    public function getBatchID()
    {
        return $this->BatchID;
    }

    /**
     * Generated from protobuf field <code>string BatchID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBatchID($var)
    {
        GPBUtil::checkString($var, True);
        $this->BatchID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .kubemq.SendQueueMessageResult Results = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->Results;
    }

    /**
     * Generated from protobuf field <code>repeated .kubemq.SendQueueMessageResult Results = 2;</code>
     * @param \Kubemq\SendQueueMessageResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Kubemq\SendQueueMessageResult::class);
        $this->Results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool HaveErrors = 3;</code>
     * @return bool
     */
    public function getHaveErrors()
    {
        return $this->HaveErrors;
    }

    /**
     * Generated from protobuf field <code>bool HaveErrors = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setHaveErrors($var)
    {
        GPBUtil::checkBool($var);
        $this->HaveErrors = $var;

        return $this;
    }

}

