<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.QueueMessageAttributes</code>
 */
class QueueMessageAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Timestamp = 1;</code>
     */
    protected $Timestamp = 0;
    /**
     * Generated from protobuf field <code>uint64 Sequence = 2;</code>
     */
    protected $Sequence = 0;
    /**
     * Generated from protobuf field <code>string MD5OfBody = 3;</code>
     */
    protected $MD5OfBody = '';
    /**
     * Generated from protobuf field <code>int32 ReceiveCount = 4;</code>
     */
    protected $ReceiveCount = 0;
    /**
     * Generated from protobuf field <code>bool ReRouted = 5;</code>
     */
    protected $ReRouted = false;
    /**
     * Generated from protobuf field <code>string ReRoutedFromQueue = 6;</code>
     */
    protected $ReRoutedFromQueue = '';
    /**
     * Generated from protobuf field <code>int64 ExpirationAt = 7;</code>
     */
    protected $ExpirationAt = 0;
    /**
     * Generated from protobuf field <code>int64 DelayedTo = 8;</code>
     */
    protected $DelayedTo = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Timestamp
     *     @type int|string $Sequence
     *     @type string $MD5OfBody
     *     @type int $ReceiveCount
     *     @type bool $ReRouted
     *     @type string $ReRoutedFromQueue
     *     @type int|string $ExpirationAt
     *     @type int|string $DelayedTo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 Timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->Timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 Timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->Timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Sequence = 2;</code>
     * @return int|string
     */
    public function getSequence()
    {
        return $this->Sequence;
    }

    /**
     * Generated from protobuf field <code>uint64 Sequence = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkUint64($var);
        $this->Sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string MD5OfBody = 3;</code>
     * @return string
     */
    public function getMD5OfBody()
    {
        return $this->MD5OfBody;
    }

    /**
     * Generated from protobuf field <code>string MD5OfBody = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMD5OfBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->MD5OfBody = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ReceiveCount = 4;</code>
     * @return int
     */
    public function getReceiveCount()
    {
        return $this->ReceiveCount;
    }

    /**
     * Generated from protobuf field <code>int32 ReceiveCount = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setReceiveCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->ReceiveCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ReRouted = 5;</code>
     * @return bool
     */
    public function getReRouted()
    {
        return $this->ReRouted;
    }

    /**
     * Generated from protobuf field <code>bool ReRouted = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setReRouted($var)
    {
        GPBUtil::checkBool($var);
        $this->ReRouted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ReRoutedFromQueue = 6;</code>
     * @return string
     */
    public function getReRoutedFromQueue()
    {
        return $this->ReRoutedFromQueue;
    }

    /**
     * Generated from protobuf field <code>string ReRoutedFromQueue = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setReRoutedFromQueue($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReRoutedFromQueue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ExpirationAt = 7;</code>
     * @return int|string
     */
    public function getExpirationAt()
    {
        return $this->ExpirationAt;
    }

    /**
     * Generated from protobuf field <code>int64 ExpirationAt = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpirationAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->ExpirationAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 DelayedTo = 8;</code>
     * @return int|string
     */
    public function getDelayedTo()
    {
        return $this->DelayedTo;
    }

    /**
     * Generated from protobuf field <code>int64 DelayedTo = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelayedTo($var)
    {
        GPBUtil::checkInt64($var);
        $this->DelayedTo = $var;

        return $this;
    }

}

