<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.ReceiveQueueMessagesRequest</code>
 */
class ReceiveQueueMessagesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     */
    protected $RequestID = '';
    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     */
    protected $ClientID = '';
    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     */
    protected $Channel = '';
    /**
     * Generated from protobuf field <code>int32 MaxNumberOfMessages = 4;</code>
     */
    protected $MaxNumberOfMessages = 0;
    /**
     * Generated from protobuf field <code>int32 WaitTimeSeconds = 5;</code>
     */
    protected $WaitTimeSeconds = 0;
    /**
     * Generated from protobuf field <code>bool IsPeak = 6;</code>
     */
    protected $IsPeak = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RequestID
     *     @type string $ClientID
     *     @type string $Channel
     *     @type int $MaxNumberOfMessages
     *     @type int $WaitTimeSeconds
     *     @type bool $IsPeak
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @return string
     */
    public function getRequestID()
    {
        return $this->RequestID;
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestID($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @return string
     */
    public function getClientID()
    {
        return $this->ClientID;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ClientID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 MaxNumberOfMessages = 4;</code>
     * @return int
     */
    public function getMaxNumberOfMessages()
    {
        return $this->MaxNumberOfMessages;
    }

    /**
     * Generated from protobuf field <code>int32 MaxNumberOfMessages = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxNumberOfMessages($var)
    {
        GPBUtil::checkInt32($var);
        $this->MaxNumberOfMessages = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 WaitTimeSeconds = 5;</code>
     * @return int
     */
    public function getWaitTimeSeconds()
    {
        return $this->WaitTimeSeconds;
    }

    /**
     * Generated from protobuf field <code>int32 WaitTimeSeconds = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setWaitTimeSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->WaitTimeSeconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsPeak = 6;</code>
     * @return bool
     */
    public function getIsPeak()
    {
        return $this->IsPeak;
    }

    /**
     * Generated from protobuf field <code>bool IsPeak = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsPeak($var)
    {
        GPBUtil::checkBool($var);
        $this->IsPeak = $var;

        return $this;
    }

}

