<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

if (false) {
    /**
     * This class is deprecated. Use Kubemq\Request\RequestType instead.
     * @deprecated
     */
    class Request_RequestType {}
}
class_exists(Request\RequestType::class);
@trigger_error('Kubemq\Request_RequestType is deprecated and will be removed in the next major release. Use Kubemq\Request\RequestType instead', E_USER_DEPRECATED);

