<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     */
    protected $RequestID = '';
    /**
     * Generated from protobuf field <code>.kubemq.Request.RequestType RequestTypeData = 2;</code>
     */
    protected $RequestTypeData = 0;
    /**
     * Generated from protobuf field <code>string ClientID = 3;</code>
     */
    protected $ClientID = '';
    /**
     * Generated from protobuf field <code>string Channel = 4;</code>
     */
    protected $Channel = '';
    /**
     * Generated from protobuf field <code>string Metadata = 5;</code>
     */
    protected $Metadata = '';
    /**
     * Generated from protobuf field <code>bytes Body = 6;</code>
     */
    protected $Body = '';
    /**
     * Generated from protobuf field <code>string ReplyChannel = 7;</code>
     */
    protected $ReplyChannel = '';
    /**
     * Generated from protobuf field <code>int32 Timeout = 8;</code>
     */
    protected $Timeout = 0;
    /**
     * Generated from protobuf field <code>string CacheKey = 9;</code>
     */
    protected $CacheKey = '';
    /**
     * Generated from protobuf field <code>int32 CacheTTL = 10;</code>
     */
    protected $CacheTTL = 0;
    /**
     * Generated from protobuf field <code>bytes Span = 11;</code>
     */
    protected $Span = '';
    /**
     * Generated from protobuf field <code>map<string, string> Tags = 12;</code>
     */
    private $Tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RequestID
     *     @type int $RequestTypeData
     *     @type string $ClientID
     *     @type string $Channel
     *     @type string $Metadata
     *     @type string $Body
     *     @type string $ReplyChannel
     *     @type int $Timeout
     *     @type string $CacheKey
     *     @type int $CacheTTL
     *     @type string $Span
     *     @type array|\Google\Protobuf\Internal\MapField $Tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @return string
     */
    public function getRequestID()
    {
        return $this->RequestID;
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestID($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kubemq.Request.RequestType RequestTypeData = 2;</code>
     * @return int
     */
    public function getRequestTypeData()
    {
        return $this->RequestTypeData;
    }

    /**
     * Generated from protobuf field <code>.kubemq.Request.RequestType RequestTypeData = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRequestTypeData($var)
    {
        GPBUtil::checkEnum($var, \Kubemq\Request\RequestType::class);
        $this->RequestTypeData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 3;</code>
     * @return string
     */
    public function getClientID()
    {
        return $this->ClientID;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ClientID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Channel = 4;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * Generated from protobuf field <code>string Channel = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Metadata = 5;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->Metadata;
    }

    /**
     * Generated from protobuf field <code>string Metadata = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->Metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 6;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->Body;
    }

    /**
     * Generated from protobuf field <code>bytes Body = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->Body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ReplyChannel = 7;</code>
     * @return string
     */
    public function getReplyChannel()
    {
        return $this->ReplyChannel;
    }

    /**
     * Generated from protobuf field <code>string ReplyChannel = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setReplyChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->ReplyChannel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Timeout = 8;</code>
     * @return int
     */
    public function getTimeout()
    {
        return $this->Timeout;
    }

    /**
     * Generated from protobuf field <code>int32 Timeout = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkInt32($var);
        $this->Timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CacheKey = 9;</code>
     * @return string
     */
    public function getCacheKey()
    {
        return $this->CacheKey;
    }

    /**
     * Generated from protobuf field <code>string CacheKey = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setCacheKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->CacheKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 CacheTTL = 10;</code>
     * @return int
     */
    public function getCacheTTL()
    {
        return $this->CacheTTL;
    }

    /**
     * Generated from protobuf field <code>int32 CacheTTL = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setCacheTTL($var)
    {
        GPBUtil::checkInt32($var);
        $this->CacheTTL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes Span = 11;</code>
     * @return string
     */
    public function getSpan()
    {
        return $this->Span;
    }

    /**
     * Generated from protobuf field <code>bytes Span = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSpan($var)
    {
        GPBUtil::checkString($var, False);
        $this->Span = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Tags = 12;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->Tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> Tags = 12;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Tags = $arr;

        return $this;
    }

}

