<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.StreamQueueMessagesRequest</code>
 */
class StreamQueueMessagesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     */
    protected $RequestID = '';
    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     */
    protected $ClientID = '';
    /**
     * Generated from protobuf field <code>.kubemq.StreamRequestType StreamRequestTypeData = 3;</code>
     */
    protected $StreamRequestTypeData = 0;
    /**
     * Generated from protobuf field <code>string Channel = 4;</code>
     */
    protected $Channel = '';
    /**
     * Generated from protobuf field <code>int32 VisibilitySeconds = 5;</code>
     */
    protected $VisibilitySeconds = 0;
    /**
     * Generated from protobuf field <code>int32 WaitTimeSeconds = 6;</code>
     */
    protected $WaitTimeSeconds = 0;
    /**
     * Generated from protobuf field <code>uint64 RefSequence = 7;</code>
     */
    protected $RefSequence = 0;
    /**
     * Generated from protobuf field <code>.kubemq.QueueMessage ModifiedMessage = 8;</code>
     */
    protected $ModifiedMessage = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RequestID
     *     @type string $ClientID
     *     @type int $StreamRequestTypeData
     *     @type string $Channel
     *     @type int $VisibilitySeconds
     *     @type int $WaitTimeSeconds
     *     @type int|string $RefSequence
     *     @type \Kubemq\QueueMessage $ModifiedMessage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @return string
     */
    public function getRequestID()
    {
        return $this->RequestID;
    }

    /**
     * Generated from protobuf field <code>string RequestID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestID($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @return string
     */
    public function getClientID()
    {
        return $this->ClientID;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ClientID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kubemq.StreamRequestType StreamRequestTypeData = 3;</code>
     * @return int
     */
    public function getStreamRequestTypeData()
    {
        return $this->StreamRequestTypeData;
    }

    /**
     * Generated from protobuf field <code>.kubemq.StreamRequestType StreamRequestTypeData = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStreamRequestTypeData($var)
    {
        GPBUtil::checkEnum($var, \Kubemq\StreamRequestType::class);
        $this->StreamRequestTypeData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Channel = 4;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * Generated from protobuf field <code>string Channel = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 VisibilitySeconds = 5;</code>
     * @return int
     */
    public function getVisibilitySeconds()
    {
        return $this->VisibilitySeconds;
    }

    /**
     * Generated from protobuf field <code>int32 VisibilitySeconds = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setVisibilitySeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->VisibilitySeconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 WaitTimeSeconds = 6;</code>
     * @return int
     */
    public function getWaitTimeSeconds()
    {
        return $this->WaitTimeSeconds;
    }

    /**
     * Generated from protobuf field <code>int32 WaitTimeSeconds = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setWaitTimeSeconds($var)
    {
        GPBUtil::checkInt32($var);
        $this->WaitTimeSeconds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 RefSequence = 7;</code>
     * @return int|string
     */
    public function getRefSequence()
    {
        return $this->RefSequence;
    }

    /**
     * Generated from protobuf field <code>uint64 RefSequence = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRefSequence($var)
    {
        GPBUtil::checkUint64($var);
        $this->RefSequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kubemq.QueueMessage ModifiedMessage = 8;</code>
     * @return \Kubemq\QueueMessage
     */
    public function getModifiedMessage()
    {
        return isset($this->ModifiedMessage) ? $this->ModifiedMessage : null;
    }

    public function hasModifiedMessage()
    {
        return isset($this->ModifiedMessage);
    }

    public function clearModifiedMessage()
    {
        unset($this->ModifiedMessage);
    }

    /**
     * Generated from protobuf field <code>.kubemq.QueueMessage ModifiedMessage = 8;</code>
     * @param \Kubemq\QueueMessage $var
     * @return $this
     */
    public function setModifiedMessage($var)
    {
        GPBUtil::checkMessage($var, \Kubemq\QueueMessage::class);
        $this->ModifiedMessage = $var;

        return $this;
    }

}

