<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

if (false) {
    /**
     * This class is deprecated. Use Kubemq\Subscribe\SubscribeType instead.
     * @deprecated
     */
    class Subscribe_SubscribeType {}
}
class_exists(Subscribe\SubscribeType::class);
@trigger_error('Kubemq\Subscribe_SubscribeType is deprecated and will be removed in the next major release. Use Kubemq\Subscribe\SubscribeType instead', E_USER_DEPRECATED);

