<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>kubemq.Subscribe</code>
 */
class Subscribe extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kubemq.Subscribe.SubscribeType SubscribeTypeData = 1;</code>
     */
    protected $SubscribeTypeData = 0;
    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     */
    protected $ClientID = '';
    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     */
    protected $Channel = '';
    /**
     * Generated from protobuf field <code>string Group = 4;</code>
     */
    protected $Group = '';
    /**
     * Generated from protobuf field <code>.kubemq.Subscribe.EventsStoreType EventsStoreTypeData = 5;</code>
     */
    protected $EventsStoreTypeData = 0;
    /**
     * Generated from protobuf field <code>int64 EventsStoreTypeValue = 6;</code>
     */
    protected $EventsStoreTypeValue = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $SubscribeTypeData
     *     @type string $ClientID
     *     @type string $Channel
     *     @type string $Group
     *     @type int $EventsStoreTypeData
     *     @type int|string $EventsStoreTypeValue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kubemq::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kubemq.Subscribe.SubscribeType SubscribeTypeData = 1;</code>
     * @return int
     */
    public function getSubscribeTypeData()
    {
        return $this->SubscribeTypeData;
    }

    /**
     * Generated from protobuf field <code>.kubemq.Subscribe.SubscribeType SubscribeTypeData = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSubscribeTypeData($var)
    {
        GPBUtil::checkEnum($var, \Kubemq\Subscribe\SubscribeType::class);
        $this->SubscribeTypeData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @return string
     */
    public function getClientID()
    {
        return $this->ClientID;
    }

    /**
     * Generated from protobuf field <code>string ClientID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientID($var)
    {
        GPBUtil::checkString($var, True);
        $this->ClientID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->Channel;
    }

    /**
     * Generated from protobuf field <code>string Channel = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->Channel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Group = 4;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->Group;
    }

    /**
     * Generated from protobuf field <code>string Group = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->Group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kubemq.Subscribe.EventsStoreType EventsStoreTypeData = 5;</code>
     * @return int
     */
    public function getEventsStoreTypeData()
    {
        return $this->EventsStoreTypeData;
    }

    /**
     * Generated from protobuf field <code>.kubemq.Subscribe.EventsStoreType EventsStoreTypeData = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setEventsStoreTypeData($var)
    {
        GPBUtil::checkEnum($var, \Kubemq\Subscribe\EventsStoreType::class);
        $this->EventsStoreTypeData = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 EventsStoreTypeValue = 6;</code>
     * @return int|string
     */
    public function getEventsStoreTypeValue()
    {
        return $this->EventsStoreTypeValue;
    }

    /**
     * Generated from protobuf field <code>int64 EventsStoreTypeValue = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventsStoreTypeValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->EventsStoreTypeValue = $var;

        return $this;
    }

}

