<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubemq.proto

namespace Kubemq;

if (false) {
    /**
     * This class is deprecated. Use Kubemq\Subscribe\EventsStoreType instead.
     * @deprecated
     */
    class Subscribe_EventsStoreType {}
}
class_exists(Subscribe\EventsStoreType::class);
@trigger_error('Kubemq\Subscribe_EventsStoreType is deprecated and will be removed in the next major release. Use Kubemq\Subscribe\EventsStoreType instead', E_USER_DEPRECATED);

